///*********************************************************************
//*                                                                    *
//*                SEGGER Microcontroller GmbH & Co. KG                *
//*        Solutions for real time microcontroller applications        *
//*                                                                    *
//**********************************************************************
//*                                                                    *
//* C-file generated by:                                               *
//*                                                                    *
//*        GUI_Builder for emWin version 5.32                          *
//*        Compiled Oct  8 2015, 11:59:02                              *
//*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
//*                                                                    *
//**********************************************************************
//*                                                                    *
//*        Internet: www.segger.com  Support: support@segger.com       *
//*                                                                    *
//**********************************************************************
//*/
//
//// USER START (Optionally insert additional includes)
//// USER END
//
//#include "DIALOG.h"
//#include "stm32f4xx.h"
//
///*********************************************************************
//*
//*       Defines
//*
//**********************************************************************
//*/
//#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
//#define ID_MULTIPAGE_0 (GUI_ID_USER + 0x01)
//#define ID_TEXT_0 (GUI_ID_USER + 0x02)
//
//
//// USER START (Optionally insert additional defines)
//extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial16;//font 
//// USER END
//
///*********************************************************************
//*
//*       Static data
//*
//**********************************************************************
//*/
//
//// USER START (Optionally insert additional static data)
//
//// USER END
//
///*********************************************************************
//*
//*       _aDialogCreate
//*/
//static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//  { FRAMEWIN_CreateIndirect, "Регистратор регулировок СУ", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x0, 0 },
//  { MULTIPAGE_CreateIndirect, "Регистратор регулировок СУ", ID_MULTIPAGE_0, 0, 0, 312, 219, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "123", ID_TEXT_0, 134, 128, 46, 17, 0, 0x0, 0 },
//  // USER START (Optionally insert additional widgets)
//  // USER END
//};
//
//
///*********************************************************************
//*
//*       Static code
//*
//**********************************************************************
//*/
//
//// USER START (Optionally insert additional static code)
//
//// USER END
//
///*********************************************************************
//*
//*       _cbDialog
//*/
//static void _cbDialog(WM_MESSAGE * pMsg) {
//  WM_HWIN hItem;
//  int     NCode;
//  int     Id;
//  // USER START (Optionally insert additional variables)
//  // USER END
//  switch (pMsg->MsgId) {
//  case WM_INIT_DIALOG:
//    //initialization of "Framewin"
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0);
//    FRAMEWIN_SetFont(hItem, &GUI_FontArial16);
//    //
//    // Initialization of 'Multipage'
//    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
//    MULTIPAGE_AddEmptyPage(hItem, 0, "Эксплуатационные");
//    MULTIPAGE_AddEmptyPage(hItem, 0, "Наработки");
//    MULTIPAGE_SetFont(hItem, &GUI_FontArial16);
//    //
//    // Initialization of 'Textbox'
//    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//    TEXT_SetFont(hItem, &GUI_FontArial16);
//    // USER START (Optionally insert additional code for further widget initialization)
//    // USER END
//    break;
//  case WM_NOTIFY_PARENT:
//    Id    = WM_GetId(pMsg->hWinSrc);
//    NCode = pMsg->Data.v;
//    switch(Id) {
//    case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        //GUI_SendKeyMsg(GUI_KEY_PGDOWN,1);
//        GUI_DispStringHCenterAt((GUI_GetVersionString()), 160, 50);
//        //MULTIPAGE_AddEmptyPage(hItem, 0, "Наработки");
//        // USER END
//        break;
//      case WM_NOTIFICATION_MOVED_OUT:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_VALUE_CHANGED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
//    // USER START (Optionally insert additional code for further Ids)
//    // USER END
//    }
//    break;
//  // USER START (Optionally insert additional message handling)
//  // USER END
//  default:
//    WM_DefaultProc(pMsg);
//    break;
//  }
//}
//
///*********************************************************************
//*
//*       Public code
//*
//**********************************************************************
//*/
///*********************************************************************
//*
//*       Createtest
//*/
//WM_HWIN Createtest(void);
//WM_HWIN Createtest(void) {
//  WM_HWIN hWin;
//
//  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
//  return hWin;
//}
//
//// USER START (Optionally insert additional public code)
//// USER END


/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
**********************************************************************
*                                                                    *
*        (c) 1996 - 2016  SEGGER Microcontroller GmbH & Co. KG       *
*                                                                    *
*        Internet: www.segger.com    Support:  support@segger.com    *
*                                                                    *
**********************************************************************

** emWin V5.38 - Graphical user interface for embedded applications **
emWin is protected by international copyright laws.   Knowledge of the
source code may not be used to write a similar product.  This file may
only  be used  in accordance  with  a license  and should  not be  re-
distributed in any way. We appreciate your understanding and fairness.
----------------------------------------------------------------------
File        : WIDGET_Multipage.c
Purpose     : Demonstrates the use of the MULTIPAGE widget
Requirements: WindowManager - (x)
              MemoryDevices - (x)
              AntiAliasing  - ( )
              VNC-Server    - ( )
              PNG-Library   - ( )
              TrueTypeFonts - ( )
---------------------------END-OF-HEADER------------------------------
*/

#include <stdlib.h>

#include "GUI.h"
#include "MULTIPAGE.h"
#include "XPT2046.h"


unsigned char touch_en;
int touch_y, touch_x;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
//
// Recommended memory to run the sample with adequate performance
//
#define RECOMMENDED_MEMORY (1024L * 20)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       Dialog resource
*
*  These tables contain the information required to create the dialogs.
*  It has been created manually, but could also be created by the GUIBuilder.
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate1[] = {
  { WINDOW_CreateIndirect,    "Dialog 1", 0,                   0,   0, 260, 100, FRAMEWIN_CF_MOVEABLE },
  { BUTTON_CreateIndirect,    "Button",   GUI_ID_BUTTON0,      5,  30,  80,  20, 0},
  { TEXT_CreateIndirect,      "Dialog 1", 0,                   5,  10,  50,  20, TEXT_CF_LEFT }
};

static const GUI_WIDGET_CREATE_INFO _aDialogCreate2[] = {
  { WINDOW_CreateIndirect,    "Dialog 2", 0,                   0,   0, 260, 100, FRAMEWIN_CF_MOVEABLE },
  { CHECKBOX_CreateIndirect,  "",         GUI_ID_CHECK0,       5,  30,   0,   0, 0},
  { CHECKBOX_CreateIndirect,  "",         GUI_ID_CHECK1,       5,  50,   0,   0, 0},
  { TEXT_CreateIndirect,      "Select 0", GUI_ID_TEXT0,       25,  30,  50,  15, TEXT_CF_LEFT },
  { TEXT_CreateIndirect,      "Select 1", GUI_ID_TEXT1,       25,  50,  50,  15, TEXT_CF_LEFT },
  { TEXT_CreateIndirect,      "Dialog 2", 0,                   5,  10,  50,  20, TEXT_CF_LEFT }
};

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       MainTask
*/
void MainTask(void) {
  WM_HWIN hMultiPage;
  WM_HWIN hFrameWin;
  WM_HWIN hDialog;

  //
  // Enable use of memory devices
  //
  WM_SetCreateFlags(WM_CF_MEMDEV);
  //GUI_Init();
  //
  // Check if recommended memory for the sample is available
  //
  if (GUI_ALLOC_GetNumFreeBytes() < RECOMMENDED_MEMORY) {
    GUI_ErrorOut("Not enough memory available.");
    return;
  }
 
  //
  // Create the frame window
  //
  hFrameWin = FRAMEWIN_Create("FrameWindow", NULL, WM_CF_SHOW, 0, 0, 320, 240);
  FRAMEWIN_SetClientColor(hFrameWin, GUI_GREEN);
  FRAMEWIN_SetActive(hFrameWin, 1);
  //FRAMEWIN_SetMoveable(hFrameWin, 1);
  //
  // Create the MULTIPAGE widget
  //
  hMultiPage = MULTIPAGE_CreateEx(7, 6, 220, 120, WM_GetClientWindow(hFrameWin), WM_CF_SHOW, 0, 0);
  GUI_Delay(500);
  //
  // Create and attach the MULTIPAGE dialog windows
  //
  hDialog = GUI_CreateDialogBox(_aDialogCreate1, GUI_COUNTOF(_aDialogCreate1), NULL,       WM_UNATTACHED, 0, 0);
  MULTIPAGE_AddPage(hMultiPage, hDialog, "Page 1");
  GUI_Delay(500);
  hDialog = GUI_CreateDialogBox(_aDialogCreate2, GUI_COUNTOF(_aDialogCreate2), NULL,       WM_UNATTACHED, 0, 0);
  MULTIPAGE_AddPage(hMultiPage, hDialog, "Page 2");
  GUI_Delay(500);
  MULTIPAGE_SelectPage(hMultiPage,0);
    WM_SetFocus(hMultiPage);
  while (1) {
    GetTouchState();
    if(touch_en==1){
    Usrednenie_XY(touch_x,touch_y,10);
    Callibrate();
    }
    GUI_SendKeyMsg(GUI_KEY_PGUP,1);
    GUI_Delay(200);
    
    
  }
}

/*************************** End of file ****************************/
